server:
  port: 8080

load_balancer:
  strategy: least_connections

health:
  interval: 3s
  timeout: 2s

proxy:
  timeout: 5s
  retries: 2

backends:
  - url: "http://backend1:8000"
  - url: "http://backend2:8000"

rate_limit:
  enabled: false
  requests_per_second: 1000
  burst: 2000
